version: 2.1

defaults:
  working_directory: ~/project

executors:
  ci:
    docker:
      - image: cimg/base:2024.11-slim

commands:
  restart_service:
    parameters:
      service_name:
        type: string
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:0JgoOo+PO4Mp19b3ZkJ7BfWmo8dzLFS+e6ryCmJ2u1s"
      - run:
          name: restart << parameters.service_name >> service
          command: |
            ssh -o StrictHostKeyChecking=accept-new \
                -o BatchMode=yes \
                -o ConnectTimeout=10 \
                -o ServerAliveInterval=60 \
                -o ServerAliveCountMax=3 \
                -o UserKnownHostsFile=/dev/null \
                "$DEPLOYER_USER"@velocorner.com "/opt/velocorner/service-update.sh << parameters.service_name >>"
          no_output_timeout: 5m

jobs:
  deploy_rates-backend:
    executor: ci
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: dockerhub login
          command: docker login -u peregin -p $DOCKERHUB_PASSWORD docker.io
      - run:
          name: deploy exchange-rate service
          command: ./deploy.sh

  restart_stack:
    executor: ci
    resource_class: small
    steps:
      - restart_service:
          service_name: rates

workflows:
  ci_cd:
    jobs:
      - deploy_rates-backend:
          context: peregin
          filters:
            branches:
              only: /^master.*/
      - restart_stack:
          context: peregin
          requires:
            - deploy_rates-backend
