version: 2.1

defaults:
  working_directory: ~/project

jobs:
  deploy_rates-backend:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: dockerhub login
          command: docker login -u peregin -p $DOCKERHUB_PASSWORD docker.io
      - run:
          name: deploy exchange-rate service
          command: ./deploy.sh

  restart_stack:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$DEPLOYER_USER"@velocorner.com '/opt/velocorner/service-update.sh rates'

workflows:
  ci_cd:
    jobs:
      - deploy_rates-backend:
          filters:
            branches:
              only: /master.*/
      - restart_stack:
          requires:
            - deploy_rates-backend
