version: 2.1

defaults:
  working_directory: ~/project

jobs:
  deploy_rates-backend:
    docker:
      - image: cimg/base:2024.09
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: dockerhub login
          command: docker login -u peregin -p $DOCKERHUB_PASSWORD docker.io
      - run:
          name: deploy exchange-rate service
          command: ./deploy.sh

  restart_stack:
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:0JgoOo+PO4Mp19b3ZkJ7BfWmo8dzLFS+e6ryCmJ2u1s"
      - run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$DEPLOYER_USER"@velocorner.com '/opt/velocorner/service-update.sh rates'

workflows:
  ci_cd:
    jobs:
      - deploy_rates-backend:
          filters:
            branches:
              only: /master.*/
      - restart_stack:
          requires:
            - deploy_rates-backend
